### ISSUE TITLE
TODO Development Tasks

### ISSUE THREAD

**Issue by jmitchell81** [FertigLab/dominoSignal#5]
## Overview

Task list for development priorities for domino

## Intended Outcome

Serves as a central resource for highlighting developments or bugs to address and sharing them with the team who will track when these tasks are accomplished.

# Task List

## High priority
- [x] Disregard complex interactions when using gene ortholog conversions
- [x] Add example usage to all function documentation
- [x] #138

## Priority
- [x] Edit gene conversion to use first returned ortholog
- [x] Ensure Domino classes are compliant with S4 standards https://adv-r.hadley.nz/s4.html
- [x] Include helper function for reformatting CellTalkDB mouse or human databases http://tcm.zju.edu.cn/celltalkdb/
- [x] If using a Seurat object as input data, add dependent of the Seurat package to read the active Assay
- [x] Clarify the formatting of the tf.activity matrix to match gene x cell formatting used in R as opposed to Python cell x gene
- [x] test outputs and plotting when running Domino without clustering
- [x] The help text for build_domino is incomplete, the description for the first 2 options is missing
- [x] Clarify that counts matrix must have gene names as row names for for expression checks
- [x] Update references to domino package name to Domino2

## CI/CD & maintenance ##
- [x] #46

## Complete
- [x] Allow alternative biomaRt mirrors for gene ortholog conversions c96a9ab
- [x] per-cluster checks of receptor expression 82d2a97
- [x] dedicated function for cellphoneDB reference processing 971d146
- [x] Fix hard-coded receptor expression threshold for remove_rec_dropout in create_domino() 971d146
- [x] AnyMatrix for class slots replaced by dgCMatrix class 518b74a
- [x] create_rl_map_cellphonedb function is not found after the github install of domino 518b74a
- [x] Ensure transcription factor targets are tracked in the domino object https://github.com/Elisseeff-Lab/domino/issues/16#issue-1288866097 9bbcd4a
- [x] Move help text for gene_conv from create_domino to create_rl_map_cellphonedb 9474d91
- [x] Include a check for the ellipses in the auc matrix that warns and removes the ellipses for compatibility with regular searching 679cf66
- [x] Include Matrix package as a dependency to use rowSums() and allow dcGMatrix sparse formats 518b74a
- [x] Clarify variable names "features" and "df" to "tf.activity", "regulons" 9474d91
- [x] Aggregate expression of genes encoding ligand complexes in the cl_signaling matrices fdda20f
- [x] Correct the setting the correlation of receptors in regulons to 0 679cf66

**Comment by kjkrishnan** [comment]
A few additional things I've noticed as I put together vignettes:

- [ ] gene_network plot title is not working for more than one cluster in the clust argument with no OutgoingSignalingClust (it repeats "Signaling  to ___" for each cluster included)
![image](https://github.com/FertigLab/domino_development/assets/60410113/446e13ad-864e-4270-940c-6ee01a147376)
- [ ] gene_network plot giving subscript out of bounds error if vectors of clusters are passed to clust and OutgoingSignalingClust
- [ ] signaling_network gives an error requiring finite 'xlim' values when using the showIncomingSignalingClusts argument
- [ ] circos_ligand_receptor is sometimes throwing an error at the step where expression values are obtained from cl_signaling matrices (ex. LILRB2)
